kind: pipeline
type: docker
name: dotnet

steps:
  
  - name: build
    image: mcr.microsoft.com/dotnet/sdk
    commands:
      - dotnet build

  - name: test
    image: mcr.microsoft.com/dotnet/sdk
    commands:
      - dotnet test
f
